version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - flask
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net
    ports:
      - 80:80
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    networks:
      net:
        aliases:
          - flask-app
networks:
  net:
